//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e3Radio.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Queues = new HashSet<Queue>();
            this.QueueVotes = new HashSet<QueueVote>();
            this.TrackLikes = new HashSet<TrackLike>();
        }
    
        public long UserID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string FacebookLink { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Queue> Queues { get; set; }
        public virtual ICollection<QueueVote> QueueVotes { get; set; }
        public virtual ICollection<TrackLike> TrackLikes { get; set; }
    }
}
