//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e3Radio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public Queue()
        {
            this.QueueVotes = new HashSet<QueueVote>();
        }
    
        public int QueueID { get; set; }
        public long UserID { get; set; }
        public int TrackID { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DatePlayed { get; set; }
    
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QueueVote> QueueVotes { get; set; }
    }
}
