//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e3Radio.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E3RadioEntities : DbContext
    {
        public E3RadioEntities()
            : base("name=E3RadioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Queue> Queues { get; set; }
        public DbSet<QueueVote> QueueVotes { get; set; }
        public DbSet<Track> Tracks { get; set; }
        public DbSet<TrackLike> TrackLikes { get; set; }
        public DbSet<TrackPlayed> TrackPlayeds { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
